### ISSUE TITLE
Scenario not iterable

### ISSUE THREAD

**Issue by DavertMik** [testomatio/check-cucumber#10]
```

___________________________

 🗒️  File :  todomvc-tests/features/persist-todos.feature 

=  Persist Todos
 -  Todos survive a page refresh


(node:25805) UnhandledPromiseRejectionWarning: TypeError: suite.scenario is not iterable
    at /home/davert/projects/testomatio/examples/codeceptjs-cucumber/node_modules/check-cucumber/bin/check.js:19:38
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:25805) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25805) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

````

Happened when I tried to run it locally on codeceptjs-cucumber:

```
 TESTOMATIO={key} npx check-cucumber "todomvc-tests/features/*.feature" 

```

**Comment by koushikmohan1996** [comment]
Fixed
